attribute_examples = {
    "Annual Fee": [
        "annual fee of $95", "no annual fee", "$0 annual fee for first year", 
        "$75 annual fee after first year", "a $450 annual fee", "annual fee waived first year", 
        "annual fee of $39", "introductory annual fee of $0", "$95 annual fee applied", 
        "$500 annual fee with premium benefits", "$99 annual fee", "$250 yearly fee",
        "annual fee of $350", "$200 annual fee waived first year", "$99 annual fee after 12 months",
        "$0 intro annual fee", "$125 annual fee", "an annual fee of $60", "$55 annual fee",
        "annual fee of $300", "no fee for first year", "$30 fee annually", "$75 annual fee charged",
        "zero annual fee", "$700 annual membership fee", "$50 annual maintenance fee",
        "$99 per year fee", "no annual fee forever", "a yearly fee of $200", "annual fee waived",
        "annual fee of $85", "$199 annual fee", "$0 annual fee first year, $450 thereafter",
        "$40 yearly fee", "intro fee $0 for first year", "$150 annual fee",
        "$0 for first year, then $60", "$80 fee per year", "$500 recurring fee", "$20 annual fee",
        "$300 membership fee annually", "$75 yearly fee", "$90 annual fee", "$25 annual charge",
        "$55 fee each year", "no recurring annual fee", "$89 annual fee", "annual fee $49 after 1 year",
        "$30 recurring fee"
    ],
    "Sign-on Bonus.purchase_type": [
        "qualifying purchases", "dining purchases for bonus", "spend on travel", 
        "qualifying grocery purchases", "eligible dining purchases", "spend on gas", 
        "use for online shopping", "all purchases qualify", "bonus on retail purchases",
        "spend at restaurants", "qualifying travel purchases", "entertainment expenses",
        "purchase type: groceries", "all eligible transactions", "online spending",
        "bonus for travel expenses", "hotel purchases", "airline tickets",
        "purchase type: fuel", "bonus for first purchase", "restaurant purchases",
        "public transportation purchases", "qualifying subscription services", 
        "international purchases", "home improvement", "utility bill payments",
        "food delivery", "spend at supermarkets", "gas station purchases", "monthly rent",
        "mortgage payments", "streaming services", "mobile payments",
        "online food orders", "purchase at department stores", "bonus on car rentals",
        "rental car purchases", "purchase of electronics", "bonus on everyday purchases",
        "convenience store purchases", "airline purchase", "shopping center purchases",
        "vacation spending", "luxury goods purchases", "rental services", "furniture purchases",
        "pharmacy transactions", "on qualifying home goods", "electronics purchase"
    ],
    "Sign-on Bonus.condition_amount": [
        "spend $500", "$1,000 minimum spend", "qualify with $3,000", 
        "after spending $4,000", "spend $5,000", "minimum $2,500 spend",
        "spend $200", "$750 minimum purchase", "make purchases of $1,200",
        "spend $3,500", "qualify with $1,500", "minimum spend $2,000",
        "after $5,000 purchases", "spend at least $4,500", "$2,000 in purchases",
        "$3,200 qualifying spend", "spend $600 for bonus", "$900 minimum",
        "$1,800 in total spend", "qualifying spend $1,250", "$500 on qualifying purchases",
        "total spend $2,750", "minimum purchase $3,600", "spend at least $7,500",
        "minimum $8,000 spend", "$2,200 in purchases", "$1,100 required spend",
        "$750 in purchases", "qualify with $600", "spend threshold $1,800",
        "total $4,000 spend", "$5,500 minimum spend", "qualify with $2,250",
        "$3,300 in purchases", "minimum purchase $500", "spend $650 for eligibility",
        "spend at least $8,500", "$6,000 in total spend", "bonus for $3,800 spend",
        "after purchases of $2,750", "$400 minimum spend", "qualifying purchase $3,500",
        "$9,000 minimum spend", "$1,000 spend threshold", "after spending $6,000",
        "$1,300 in purchases", "minimum $1,700 spend", "$3,700 for bonus",
        "$4,800 purchase requirement"
    ],
    "Sign-on Bonus.timeframe": [
        "first 3 months", "first 90 days", "first 6 months", 
        "within 60 days", "within 120 days", "in first 12 months",
        "in 180 days", "first month of account", "first 4 months",
        "in 30 days", "first 9 months", "first 45 days", 
        "within 7 days", "within 6 months", "first 15 days", 
        "first year", "in first two months", "within first month",
        "in first quarter", "within 2 months", "by day 60",
        "first two quarters", "within 10 days", "first week", 
        "in first semester", "within half year", "initial 3 months",
        "first 30 days", "within first 180 days", "in 90 days", 
        "within 15 days", "first 20 days", "during first year",
        "in first 5 months", "first 120 days", "in 75 days", 
        "within 25 days", "within first 90 days", "first 14 days", 
        "first 10 weeks", "within 5 days", "within first quarter",
        "initial 2 months", "first 8 weeks", "first 2 quarters",
        "within first 45 days", "in first 50 days", "within 3 months"
    ],
    "Sign-on Bonus.reward_type": [
        "bonus points", "cash back", "bonus miles", 
        "statement credit", "reward points", "membership points",
        "loyalty miles", "gift card", "cash reward",
        "travel miles", "points bonus", "rewards cash",
        "shopping credits", "fuel points", "airline miles",
        "store credit", "dining points", "hotel points",
        "statement rebate", "lounge access", "air miles",
        "rewards credit", "flight miles", "e-gift card",
        "purchase discount", "balance credit", "loyalty points",
        "shopping voucher", "discount credits", "rewards",
        "trip credit", "gift voucher", "meal credits",
        "gasoline points", "subscription credit", "rewards rebate",
        "bonus rebate", "mileage points", "VIP points",
        "credit rewards", "cash bonus", "travel voucher",
        "redeemable points", "flight credits", "purchase credits",
        "rebate voucher", "VIP access", "discounted rewards",
        "gift points"
    ],
    "Sign-on Bonus.reward_amount": [
        "10,000", "20,000 points", "5,000 miles", 
        "15,000 bonus", "25,000 miles", "50,000 rewards",
        "2,000 points", "30,000 points", "5,000 bonus",
        "12,000 miles", "8,000 points", "25,000 points",
        "6,000 rewards", "3,000 miles", "100,000 points",
        "15,000 miles", "60,000 rewards", "25,000 points",
        "40,000 bonus", "35,000 points", "200,000 points",
        "80,000 bonus", "1,000 points", "10,000 miles",
        "7,500 rewards", "45,000 points", "55,000 points",
        "30,000 miles", "20,000 miles", "100,000 miles",
        "50,000 rewards", "6,000 miles", "80,000 points",
        "3,000 bonus", "15,000 points", "12,000 rewards",
        "200,000 bonus", "18,000 points", "65,000 points",
        "1,500 points", "75,000 rewards", "90,000 points",
        "5,000 miles", "25,000 rewards", "4,000 points",
        "70,000 miles", "35,000 rewards", "7,000 bonus",
        "10,000 rewards"
    ],

    "Reward Category Map.reward_unit": [
        "points per dollar", "cash back percentage", "miles per dollar",
        "rewards points per purchase", "cash rebate percentage", "fuel points per gallon",
        "points per transaction", "percentage discount", "dollars back per purchase",
        "bonus points on dining", "air miles per dollar", "cash back on total spend",
        "grocery points per dollar", "hotel points per night", "percentage off on shopping",
        "dining points per meal", "points per visit", "retail points per dollar",
        "airline points per flight", "percent back on streaming",
        "pharmacy points per transaction", "bonus points per month",
        "restaurant points per dollar", "grocery rebate per dollar",
        "dining dollars per meal", "points per gallon", "utility points per payment",
        "cashback on fuel", "miles per purchase", "food delivery points per order",
        "rewards percentage on entertainment", "discount on transportation",
        "rewards per subscription", "miles per trip", "rebate per spend category",
        "points per subscription service", "percent savings on utility bills",
        "miles earned on travel", "restaurant rewards per visit", "rebate per grocery dollar",
        "retail rewards points", "cashback percentage on food",
        "bonus points on subscriptions", "cashback on utilities", "miles per mile",
        "cash per grocery visit", "rewards on gas", "dining points per dollar"
    ],

    "Reward Category Map.reward_amount": [
        "1 point", "2 points", "3 points", "5 points", "10 points",
        "0.5% cash back", "1% cash back", "1.5% cash back", "2% cash back", "3% cash back",
        "4% cash back", "5% cash back", "0.25 miles per dollar", "0.5 miles per dollar",
        "1 mile per dollar", "1.25 miles per dollar", "2 miles per dollar",
        "1 point per dollar", "2 points per dollar", "3 points per dollar",
        "1.5% rebate", "0.75% cash back", "1.5 points per dollar",
        "0.5 points per dollar", "2.5% cash back", "1 mile", "5 miles", "10 miles",
        "0.5% rewards on groceries", "1% rewards on dining",
        "1.25 points per dollar on travel", "2 points per dollar on hotels",
        "3% rebate on electronics", "2% discount on utilities",
        "1.25% back on all purchases", "1.75 points per dollar on gas",
        "0.75% savings on dining", "0.5 points on every dollar spent",
        "1 reward point per dollar", "2.25 points per dollar",
        "1.25% cash rebate", "3 points for every $10", "2.5 miles per dollar",
        "1% on every dollar", "4 points per dollar on streaming services",
        "1.5 cash back per dollar on restaurants", "1 reward for every $5"
    ],

    "Reward Category Map.reward_threshold.on_up_to_purchase_amount_usd": [
        "$500 on dining", "$1000 on groceries", "$1500 on travel", "$2000 on gas",
        "$2500 on retail purchases", "$3000 on entertainment", "$500 on food delivery",
        "$750 on electronics", "$1000 on utilities", "$1500 on online shopping",
        "$2000 per month", "$2500 per billing cycle", "$3000 per year",
        "$4000 per quarter", "$5000 on airline tickets", "$1000 on hotel stays",
        "$600 on streaming services", "$700 on pharmacy purchases", "$800 on dining out",
        "$1200 on retail spending", "$2000 on rental cars", "$2500 on groceries",
        "$5000 for educational expenses", "$1000 on telecom services",
        "$2000 on subscription services", "$3000 on home improvement",
        "$3500 on public transport", "$500 on personal care", "$600 on health expenses",
        "$750 for wellness", "$1000 per promotion", "$1500 per category",
        "$2000 for recurring purchases", "$3000 annually on travel",
        "$500 on fuel purchases", "$800 on restaurants", "$1200 on shopping",
        "$2000 annually on groceries", "$1500 for utility bills",
        "$3000 for annual travel", "$200 on streaming", "$250 on digital content",
        "$350 on digital subscriptions", "$400 on mobile payments",
        "$600 on insurance", "$1500 on transport", "$1000 on healthcare",
        "$2000 on fitness", "$5000 per spending category"
    ],

    "Reward Category Map.reward_threshold.per_timeframe_num_months": [
        "per month", "per quarter", "annually", "biannually",
        "every 3 months", "every 6 months", "once per year",
        "each billing cycle", "per half-year", "every 4 months",
        "quarterly", "semi-annually", "every 2 months",
        "per month on grocery spend", "per month on dining",
        "each fiscal quarter", "each quarter on travel",
        "every three months on electronics", "once a year on airline",
        "monthly on retail", "yearly on gas purchases",
        "every six months on subscription services", "quarterly on groceries",
        "annually on health expenses", "per month for online shopping",
        "every 4 weeks", "every 2 weeks", "each month on utilities",
        "every quarter for dining", "every half-year on travel",
        "biannually for wellness", "annually on home improvement",
        "each month on fuel purchases", "quarterly for retail",
        "each 2-month period", "every 3-month period",
        "every fiscal year", "per season", "quarterly for electronics",
        "annually on telecom", "monthly on entertainment",
        "monthly on dining and restaurants", "every 3 months on groceries",
        "annually on gym and fitness", "quarterly on health purchases"
    ],

    "Reward Category Map.reward_threshold.fallback_reward_amount": [
        "0.5% cash back", "1% cash back", "0.25 miles per dollar", 
        "0.1% rebate", "0.5 points per dollar", "0.25 points per transaction",
        "0.2% discount", "1 reward point", "0.5% rebate",
        "0.25 dollars per transaction", "0.1 mile per dollar",
        "1% cash on all purchases", "0.1% back", "0.1 point per dollar",
        "0.05 miles per transaction", "0.15% cash rebate", "0.5 points",
        "0.1% bonus on all spend", "1 point per dollar", "0.1% on every purchase",
        "0.25% on groceries", "0.2% on dining", "0.3% on travel",
        "0.4% on gas purchases", "0.1% on retail purchases",
        "0.2% on food delivery", "0.25% for online shopping",
        "0.15% for telecom services", "0.2% on subscriptions",
        "0.3% on home improvement", "0.25% on car rentals",
        "0.5% on restaurant spending", "0.15% for fuel",
        "0.3 points per dollar", "0.2% on health expenses",
        "0.3% for streaming services", "0.25% for pharmacy",
        "0.5 points on utilities", "0.15% for electronics",
        "0.2% for home services", "1 mile per 10 dollars",
        "0.05% for every spend", "0.1% on all categories",
        "0.25 points per visit", "0.2 points per transaction",
        "0.3% on gym membership", "0.4 points per dollar"
    ],
    
    "Reward Category Map.category": [
        "travel rewards", "cash back on dining", "grocery points", 
        "gas rewards", "entertainment cash back", "shopping rewards",
        "dining points", "hotel rewards", "airline points",
        "retail cash back", "restaurant cash back", "public transport rewards",
        "grocery cash back", "online shopping points", "gas station cash back",
        "pharmacy rewards", "food delivery points", "subscriptions rewards",
        "health rewards", "wellness points", "pet store cash back",
        "furniture points", "electronics rewards", "utility bill cash back",
        "travel points", "home improvement rewards", "education cash back",
        "car rental points", "office supplies rewards", "parking points",
        "airline rewards", "entertainment points", "telecom cash back",
        "utilities rewards", "food cash back", "fuel points",
        "streaming services rewards", "pharmacy cash back", "grocery rewards",
        "online spending points", "convenience store rewards", "home improvement points",
        "utility rewards", "restaurant points", "cash back on groceries",
        "shopping cash back", "rewards on gas", "dining cash back",
        "travel rewards", "rewards on transportation"
    ],
    "APR.apr": [
        "13.99% APR", "variable APR of 23.99%", "0% introductory APR", 
        "15.99% APR after 12 months", "regular APR 14.99%", "APR for cash advances 25.99%", 
        "19.99% standard APR", "27.99% penalty APR", "22.49% for purchases", 
        "17.24% variable APR", "19.24% purchase APR", "10.99% introductory APR", 
        "APR between 12.99% and 22.99%", "balance transfer APR 0%", "purchase APR 18.49%", 
        "0% APR on purchases", "standard APR 17.49%", "26.99% cash advance APR", 
        "penalty APR of 29.99%", "variable APR based on Prime Rate", "13.24% APR", 
        "APR ranges from 12.99% to 21.99%", "17.99% APR for new purchases", "fixed APR of 24.99%", 
        "23.99% APR for balance transfers", "25.24% APR", "18.74% APR on all purchases", 
        "variable rate APR", "22.99% APR for late payments", "standard purchase APR 16.99%", 
        "cash advance APR 26.24%", "19.99% APR for purchases", "APR fixed at 20.99%", 
        "25.74% APR", "27.99% APR for missed payments", "balance transfer APR 15.99%", 
        "intro APR 0% for 12 months", "APR of 21.99%", "24.99% APR after 6 months", 
        "cash advance APR of 28.99%", "penalty APR at 30.99%", "16.24% APR", 
        "12.74% APR for new customers", "intro APR of 0% for 15 months", "29.99% for penalties", 
        "APR of 14.74%", "purchase APR from 16.99%", "APR varies by Prime Rate", 
        "26.49% APR for missed payments", "variable APR 18.99%"
    ],
    "Benefits": [
        "airport lounge access", "travel insurance", "extended warranty", 
        "24/7 concierge", "fraud protection", "cell phone insurance", 
        "no foreign transaction fees", "car rental insurance", "price protection", 
        "identity theft protection", "purchase protection", "lost luggage coverage", 
        "trip cancellation insurance", "roadside assistance", "emergency card replacement", 
        "VIP experiences", "baggage delay insurance", "free credit score", 
        "discounts on hotels", "emergency medical assistance", "zero liability for fraud", 
        "access to exclusive events", "concierge services", "purchase assurance", 
        "price match guarantee", "return protection", "free airport lounge entry", 
        "airline discounts", "extended returns", "shopper’s protection", 
        "luxury concierge services", "access to presale tickets", "free car rental upgrade", 
        "cash advance with protection", "global entry reimbursement", "purchase rewards program", 
        "priority boarding", "price drop protection", "emergency travel assistance", 
        "VIP shopping experiences", "concierge for travel booking", "free shipping on purchases", 
        "complimentary travel coverage", "trip delay reimbursement", "insurance on checked bags", 
        "hotel discounts", "cash advance security", "rewards on purchases", 
        "bonus rewards on selected items", "security for online transactions"
    ],
    "Credit Needed": [
        "Excellent credit", "Good to excellent credit", "Fair credit", 
        "Poor credit accepted", "No credit required", "Prime credit recommended", 
        "Credit score above 700", "Strong credit profile", "Limited credit history ok", 
        "Requires 750+ score", "Fair to excellent credit", "Requires a minimum of 680", 
        "Good credit history", "Bad credit ok", "No prior credit necessary", 
        "New credit history acceptable", "Established credit needed", "Ideal for excellent credit", 
        "Credit score minimum 650", "Limited credit ok", "Poor to fair credit", 
        "Credit score above 720", "750 or higher credit", "Low credit acceptable", 
        "No credit required", "Good credit score", "Very good to excellent credit", 
        "Credit score over 700", "Credit history required", "Minimum score 680", 
        "Strong credit required", "Suitable for good credit", "Excellent credit only", 
        "Fair to good credit", "Requires high credit score", "Credit history necessary", 
        "Prime credit needed", "No credit check", "Credit rating of 700+", 
        "Credit above 600 required", "Score of 680 needed", "Poor credit ok", 
        "Suitable for limited credit", "Requires no prior history", "Good to prime credit", 
        "Credit score minimum 700", "Excellent history recommended", "Some credit required", 
        "Requires limited credit", "Minimum credit score 660"
    ]
}
